when:
  - event: push
    branch: main

steps:
  - name: checkout
    image: woodpeckerci/plugin-git
    settings:
      depth: 50 # optional, fetches more history if needed

  - name: enable-corepack-and-install
    image: node:lts
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate # optional but ensures latest pnpm
      - pnpm install --frozen-lockfile # safer for CI
      - pnpm dlx nuxt generate

  - name: publish to build branch
    image: alpine/git
    environment:
      GIT_TOKEN:
        from_secret: git_token
    commands:
      # - echo "== WORKSPACE =="
      # - pwd
      # - ls /
      # - echo "== FIND DIST =="
      # - find / -type d -name .output 2>/dev/null || echo "No dist folder found anywhere"
      # - echo "== WOODPECKER SRC =="
      # - ls /woodpecker/src || echo "No /woodpecker/src"

      - git config --global user.email "54786476+Tauromachian@users.noreply.github.com"
      - git config --global user.name "Tauromachian"

      - git clone https://github.com/Tauromachian/home-finances.git repo
      - cd repo
      - git checkout build || git checkout -b build
      - find . -mindepth 1 -not -path './.git*' -delete

      - cp -r /woodpecker/src/github.com/Tauromachian/home-finances/.output/public/. .

      - git remote set-url origin https://$GIT_TOKEN@github.com/Tauromachian/home-finances.git
      - git add .
      - git diff --cached --quiet || git commit -m "Build ${CI_COMMIT_SHA} - ${CI_COMMIT_MESSAGE}"
      - git push --force origin build
